Back/railsback/config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'site/index'
  # resources :sites, :categories

  resources :sites, :categories, :messages, defaults: { format: 'json' }
end

Back/railsback/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Back/railsback/app/models/category.rb
class Category < ApplicationRecord
end

Back/railsback/app/models/message.rb
class Message 
    include ActiveModel::Model
    attr_accessor :email, :subject, :text
    validates :email, :subject, :text, presence: true
end

Back/railsback/app/models/site.rb
class Site < ApplicationRecord

    # logger.debug :picture
    mount_base64_uploader :picture, PictureUploader
    # mount_uploaders :picture, PictureUploader
    # mount_uploader :picture, PictureUploader
    # has_many :multipics
    # attr_accessor :document_data
    # attr_accessor :multipic_data
    # serialize :picture, JSON
end

Back/railsback/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :omniauthable
  include DeviseTokenAuth::Concerns::User
end

Back/railsback/app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  include DeviseTokenAuth::Concerns::SetUserByToken
  # protect_from_forgery with: :exception
    include ActionController::MimeResponds  
    rescue_from ActionView::MissingTemplate do |exception|
    end 
    config.logger = Logger.new(STDOUT)
end

Back/railsback/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        
        respond_to do |format|
            if @category.save
                format.json{render @category, status: :created, location: @category}
            else
                render 'new'
            end
        end
    end

    def index
        @category = Category.all
        respond_to do |format|
            format.json {render json: @category}
        end
    end

    def show
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        respond_to do |format|
            if @category.update(category_params)
                format.json { render :show, status: :created, location: @category }
            else
                render 'edit'
            end
        end
    end

    def destroy
        @category = Category.find(params[:id])
        @category.destroy
        respond_to do |format|
            format.json {head :no_content}
            redirect_to categories_path
        end
    end

    private 
    def category_params 
        params.require(:category).permit(:title)
    end

end

Back/railsback/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.valid?
      MessageMailer.contact(@message).deliver
    else
      render :new
    end
  end

  private
    def message_params
        params.require(:message).permit(:email, :subject, :text)
    end
end

Back/railsback/app/controllers/sites_controller.rb
class SitesController < ApplicationController
    
    def new
        @site = Site.new
    end
    
    def create
        @site = Site.new(site_params)
        respond_to do |format|
            if @site.save
                format.json{render @site, status: :created, location: @site}
            else
                render 'new'
            end
        end
    end

    def index
        @sites = Site.all
        respond_to do |format|
            format.html
            format.json { render json: @sites }
        end
    end

    def show
        @site = Site.find(params[:id])
    end

    def update
        @site = Site.find(params[:id])
        respond_to do |format|
            if @site.update(site_params)
                format.json { render :show, status: :created, location: @site }
            else
                render 'edit'
            end
        end
    end

    def destroy
        @site = Site.find(params[:id])
        @site.destroy
        respond_to do |format|
            format.json {head :no_content}
            redirect_to sites_path
        end
    end

    private 
    def site_params 
        params.require(:site).permit(:description, :title, :category, :picture)
    end
end

Back/railsback/app/helpers/application_helper.rb
module ApplicationHelper
end

Back/railsback/app/helpers/categories_helper.rb
module CategoriesHelper
end

Back/railsback/app/helpers/sites_helper.rb
module SitesHelper
end

Back/railsback/app/views/categories/index.html.erb
<h1>Category</h1>

Back/railsback/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsback</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Back/railsback/app/views/messages/_body.html.erb
<%= @body %>

Back/railsback/app/views/messages/_form.html.erb
<%= form_for @site do |f| %>
<% cache f do %>
<p>
        <%= f.label :email %>
        <%= f.text_field :email %>
    <p>
        <%= f.label :subject %>
        <%= f.text_area :subject %>
    </p>
    <p>
        <%= f.label :text %>
        <%= f.text_field :text %>
    </p>

    <p>
    <%= f.submit %>
    </p>    
</p>
<% end %>
<% end %>

<%= link_to "Back to Main Page", sites_path%>

Back/railsback/app/views/messages/contact.html.erb
<h1>Create</h1>

<%= render "body" %>

Back/railsback/app/views/messages/new.html.erb
<h1>Create</h1>

<%= render "form" %>

Back/railsback/app/views/sites/_form.html.erb
<%= form_for @site do |f| %>
<% cache f do %>
<p>
        <%= f.label :title %>
        <%= f.text_field :title %>
    <p>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.label :imgpath %>
        <%= f.text_field :imgpath %>
    </p>
    <p>
        <%= f.label :category %>
        <%= f.text_area :category %>                               
    </p>

    <p>
    <%= f.submit %>
    </p>    
</p>
<% end %>
<% end %>

<%= link_to "Back to Main Page", sites_path%>

Back/railsback/app/views/sites/edit.html.erb
<h1>Editing</h1>

<%= render  "form" %>

Back/railsback/app/views/sites/show.html.erb
<h1>Content of "<%= @site.title %>" </h1>

<p>Title <%= @site.title %></p>

<p>Description <%= @site.description %></p>

<p>Image <%= @site.imgpath %></p>

<p>Category <%= @site.category %></p>

<%= link_to "Back to Main Page", site_path%>